import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  bookSidebar: [
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: [
        'module-1-ros2/chapter-1-ros2-fundamentals',
        'module-1-ros2/chapter-2-ros2-communication-control',
        'module-1-ros2/chapter-3-urdf-humanoid-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [
        'module-2-digital-twin/chapter-1-digital-twins-in-robotics',
        'module-2-digital-twin/chapter-2-physics-simulation-with-gazebo',
        'module-2-digital-twin/chapter-3-high-fidelity-interaction-with-unity',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3-ai-robot-brain/chapter-1-isaac-sim',
        'module-3-ai-robot-brain/chapter-2-isaac-ros',
        'module-3-ai-robot-brain/chapter-3-motion-planning',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/chapter-1-vla-foundations',
        'module-4-vla/chapter-2-voice-to-action-llms',
        'module-4-vla/chapter-3-cognitive-planning-humanoids',
      ],
    },
  ],
};

export default sidebars;
